// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZPQqqZ6MzB_-0IlEQmeTYQCffvEn5i4',
    appId: '1:122807572990:web:b09b39dc2753c12df908af',
    messagingSenderId: '122807572990',
    projectId: 'delivery-7ccaa',
    authDomain: 'delivery-7ccaa.firebaseapp.com',
    storageBucket: 'delivery-7ccaa.firebasestorage.app',
    measurementId: 'G-W0STDBVRWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKKpN0nPuVx6nLS2InPhEL5-27jwD2Gfs',
    appId: '1:122807572990:android:0fa824dd2f3d2d7ff908af',
    messagingSenderId: '122807572990',
    projectId: 'delivery-7ccaa',
    storageBucket: 'delivery-7ccaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEI4MGVCeOCn2NtPsBJyKnLyMF0MKYds8',
    appId: '1:122807572990:ios:f999e0c4eeeccb39f908af',
    messagingSenderId: '122807572990',
    projectId: 'delivery-7ccaa',
    storageBucket: 'delivery-7ccaa.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEI4MGVCeOCn2NtPsBJyKnLyMF0MKYds8',
    appId: '1:122807572990:ios:f999e0c4eeeccb39f908af',
    messagingSenderId: '122807572990',
    projectId: 'delivery-7ccaa',
    storageBucket: 'delivery-7ccaa.firebasestorage.app',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZPQqqZ6MzB_-0IlEQmeTYQCffvEn5i4',
    appId: '1:122807572990:web:122f8177e60149c8f908af',
    messagingSenderId: '122807572990',
    projectId: 'delivery-7ccaa',
    authDomain: 'delivery-7ccaa.firebaseapp.com',
    storageBucket: 'delivery-7ccaa.firebasestorage.app',
    measurementId: 'G-FJ4S7LTXXJ',
  );
}
